### ISSUE TITLE
(👉ﾟヮﾟ)👉╮(╯▽╰)╭👈(ﾟヮﾟ👈)

### ISSUE THREAD

**Issue by ghost** [c3lv/bug_of_github#1]

**Comment by syo093c** [comment]
🙇‍♂️😅🙇‍♂️
![Screen Shot 2022-05-10 at 7 26 33 PM](https://user-images.githubusercontent.com/45763662/167618148-439e4bf2-3320-42b9-90eb-dd016866e51a.jpg)
![Screen Shot 2022-05-10 at 7 26 03 PM](https://user-images.githubusercontent.com/45763662/167618060-71d83e47-1d8a-472b-9c69-6af14c06173f.jpg)
